apiVersion: apps/v1
kind: Deployment
metadata:
  name: <INSERT_NAME>
spec:
  selector:
    matchLabels:
      app: <INSERT_NAME>
  replicas: 1 # tells deployment to run X pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: <INSERT_NAME>
        image: <INSER_IMAGE_REFERENCE>
        imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: <INSERT_NAME>
  labels:
    app: <INSERT_NAME>
spec:
  type: NodePort
  selector:
    run: <INSERT_NAME>
  ports:
   - protocol: TCP
     port: 8080
